stfalcon_tinymce:
    use_callback_tinymce_init: false
    selector: .wysiwyg
    theme:
        advanced:
#            file_browser_callback: 'elFinderBrowser'
#            skin: lightgray-gradient
            plugins:
                - 'advlist autolink lists link image charmap print preview hr anchor pagebreak'
                - 'searchreplace wordcount visualblocks visualchars code fullscreen'
                - 'insertdatetime media nonbreaking save table contextmenu directionality'
                - 'emoticons template paste textcolor'
            toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | preview media | forecolor backcolor emoticons'
            image_advtab: true
            force_br_newlines : false
            forced_root_block : ''
            convert_urls : false
            relative_urls: false
            height: 380
            width: '100%'
#            content_css: 'asset[bundles/felib/tinymce/content.css]'
        simple:
            image_advtab: false
            force_br_newlines : false
            forced_root_block : ""
            convert_urls : false
            relative_urls: false
            width: "100%"
            height: 380
            menubar: false
            toolbar: false
            statusbar: false
#            content_css: 'asset[bundles/felib/tinymce/content.css]'
