twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['form/horizontal_layout.html.twig']
    globals:
        is_user_form: "%env(bool:USER_FORM_ENABLE)%"
