version: '3.7'
services:
    nginx:
        build:
            context: ./.docker/development
            dockerfile: nginx.docker
        volumes:
            - ./:/app
        depends_on:
            - php
        ports:
            - "${WEB_PORT}:80"
    php:
        build:
            context: ./.docker/development
            dockerfile: php-fpm.docker
#            dockerfile: php-fpm-alpine.docker
        volumes:
            - ./:/app
            - composer:/root/.composer/cache
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DATABASE_URL: 'pgsql://coop:1234@db:5432/coop?serverVersion=12.2'
#            DATABASE_URL: 'mysql://coop:1234@dbmysql:3306/coop?serverVersion=5.7'
#            DATABASE_URL: 'mysql://coop:1234@dbmysql:3306/coop?serverVersion=mariadb-10.3.20'
#        depends_on:
#            - dbmysql
    db:
        build:
            context: ./.docker/development
            dockerfile: postgres.docker
        restart: unless-stopped # always
        environment:
            POSTGRES_USER: coop
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: coop
        ports:
            - 5433:5432
        volumes:
            - coop-db:/var/lib/postgresql/data
#            - ./var/lib/postgresql/data:/var/lib/postgresql/data
#    dbmysql:
#        user: "1000:50"
#        build:
#            context: ./.docker/development
#            dockerfile: mariadb.docker
#        restart: always
#        environment:
#            MYSQL_DB: coop
#            MYSQL_USER: coop
#            MYSQL_PASSWORD: 1234
#            MYSQL_ROOT_PASSWORD: 1234
#        ports:
#            - 3366:3306
#        volumes:
#            - coop-db-mysql:/var/lib/mysql/data
##            - ./var/lib/mysql/data:/var/lib/mysql/data
#        command:
#            'mysqld --innodb-flush-method=fsync'

volumes:
    composer:
    coop-db:
#    coop-db-mysql:
